# H2 Datenbank Konfiguration

spring.datasource.url=jdbc:h2:mem:eventservicedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=es
spring.datasource.password=123

# H2 Web-Oberfläche (Konsole) aktivieren
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate Einstellungen
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
 #update
spring.jpa.show-sql=true

# Verzögert die Initialisierung der Datenquelle, damit die SQL-Skripte korrekt ausgeführt werden können
spring.jpa.defer-datasource-initialization=true

# Alle SQL-Skripte ausführen, auch wenn die Datenbank bereits initialisiert ist
spring.sql.init.mode=always




###
####
###

# Ollama Einstellungen (LangChain4j)
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=llama3.2
langchain4j.ollama.chat-model.temperature=0.3
